'use client';
import {FormEvent,useEffect,useState} from 'react';
import {apiRequest,CurrentUser} from '../lib/api';
type Booking={id:string;status:string;sourceLanguage:string;targetLanguage:string;scheduledStartAt:string;scheduledEndAt:string;quotedAmountMinor:string|null;currency:string|null;meetingUrl:string|null;locationType:string;deliveryNotes:string|null;revisionNotes:string|null;service:{name:string};customer?:{email:string};interpreter?:{email:string}|null};
export default function BookingsManager({staff=false}:{staff?:boolean}) {
 const [items,setItems]=useState<Booking[]>([]);const [people,setPeople]=useState<{id:string;email:string}[]>([]);const [admin,setAdmin]=useState(false);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const reload=()=>apiRequest<Booking[]>(staff?'/interpretation/staff/bookings':'/interpretation/bookings/me').then(setItems);
 useEffect(()=>{reload().catch(e=>setMessage(e.message));if(staff)apiRequest<CurrentUser>('/auth/me').then(u=>{const a=u.roles.some(r=>['ADMIN','SUPER_ADMIN'].includes(r));setAdmin(a);if(a)apiRequest<{id:string;email:string}[]>('/interpretation/staff/interpreters').then(setPeople).catch(e=>setMessage(e.message));}).catch(e=>setMessage(e.message));},[staff]);
 async function act(id:string,action:string,event?:FormEvent<HTMLFormElement>){event?.preventDefault();const f=event?new FormData(event.currentTarget):null;setBusy(true);setMessage('');try{await apiRequest('/interpretation/bookings/'+id+'/manage',{method:'POST',body:JSON.stringify({action,...(f?Object.fromEntries([...f].filter(([,v])=>v!=='')):{})})});await reload();setMessage('Booking updated.');}catch(e){setMessage(e instanceof Error?e.message:'Update failed.');}finally{setBusy(false);}}
 return <section>{admin&&<details className="form-card"><summary>Approve an interpreter</summary><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await apiRequest('/interpretation/staff/interpreters',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});setPeople(await apiRequest('/interpretation/staff/interpreters'));setMessage('Interpreter approved.');}catch(e){setMessage(e instanceof Error?e.message:'Approval failed.');}finally{setBusy(false);}}}><label>Verified account email<input name="email" type="email" required/></label><label>Language pairs<input name="languagePairs" minLength={3} maxLength={500} required/></label><label>Reviewed qualifications<textarea name="qualifications" minLength={3} maxLength={2000} required/></label><button className="button" disabled={busy}>Approve interpreter</button></form></details>}<p role="status">{message}</p>{!items.length&&<p>No bookings to display.</p>}{items.map(b=><article className="form-card" key={b.id}><h2>{b.service.name}</h2><p>{b.sourceLanguage} → {b.targetLanguage} · {b.status.replaceAll('_',' ')}</p><p>{new Date(b.scheduledStartAt).toLocaleString()} to {new Date(b.scheduledEndAt).toLocaleString()}</p>{b.customer&&<p>Customer: {b.customer.email}</p>}{b.interpreter&&<p>Interpreter: {b.interpreter.email}</p>}{b.quotedAmountMinor&&<p>Quote: {b.currency} {(Number(b.quotedAmountMinor)/100).toLocaleString()}</p>}{b.meetingUrl&&<a href={b.meetingUrl} target="_blank" rel="noreferrer">Join session</a>}{b.deliveryNotes&&<p>Session summary: {b.deliveryNotes}</p>}{b.revisionNotes&&<p>Requested correction: {b.revisionNotes}</p>}
 {admin&&['REQUESTED','QUOTED'].includes(b.status)&&<form onSubmit={e=>act(b.id,'quote',e)}><label>Amount in minor units (100 = 1 currency unit)<input name="amountMinor" type="number" min={1} max={999999999999} required/></label><label>Currency<input name="currency" pattern="[A-Z]{3}" defaultValue="NGN" required/></label><button className="button" disabled={busy}>Send quote</button></form>}
 {!staff&&['QUOTED','PAYMENT_PENDING'].includes(b.status)&&<button className="button" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await apiRequest<{authorizationUrl:string}>('/interpretation/bookings/'+b.id+'/checkout',{method:'POST'});window.location.assign(r.authorizationUrl);}catch(e){setMessage(e instanceof Error?e.message:'Checkout failed.');setBusy(false);}}}>Pay quote</button>}
 {admin&&['CONFIRMED','INTERPRETER_ASSIGNED'].includes(b.status)&&<form onSubmit={e=>act(b.id,'assign',e)}><label>Interpreter<select name="interpreterId" required><option value="">Choose interpreter</option>{people.map(p=><option value={p.id} key={p.id}>{p.email}</option>)}</select></label><label>Secure meeting link<input name="meetingUrl" type="url" pattern="https://.*" required={b.locationType==='ONLINE'}/></label><button className="button" disabled={busy}>Assign interpreter</button></form>}
 {staff&&['INTERPRETER_ASSIGNED','REVISION_REQUIRED'].includes(b.status)&&<button className="button" disabled={busy} onClick={()=>act(b.id,'start')}>Start session / revision</button>}
 {staff&&b.status==='IN_PROGRESS'&&<form onSubmit={e=>act(b.id,'deliver',e)}><label>Session summary<textarea name="notes" minLength={3} maxLength={5000} required/></label><button className="button" disabled={busy}>Send for customer review</button></form>}
 {!staff&&b.status==='DELIVERED'&&<><button className="button" disabled={busy} onClick={()=>act(b.id,'complete')}>Accept and complete</button><form onSubmit={e=>act(b.id,'revise',e)}><label>Issue to resolve<textarea name="notes" minLength={3} maxLength={5000} required/></label><button className="button-outline" disabled={busy}>Request correction</button></form></>}
 {!staff&&['REQUESTED','QUOTED'].includes(b.status)&&<button className="button-outline" disabled={busy} onClick={()=>act(b.id,'cancel')}>Cancel request</button>}
 </article>)}</section>;
}
