
import 'reflect-metadata';
import {PrismaClient} from '@prisma/client';
import {randomBytes} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {strict as assert} from 'node:assert';
import {CoursesService} from '../src/courses/courses.service';
import {EnrollmentsService} from '../src/enrollments/enrollments.service';
import {AssessmentsService} from '../src/assessments/assessments.service';
import {LearningService} from '../src/learning/learning.service';
import {CertificatesService} from '../src/certificates/certificates.service';
import {InterpretationService} from '../src/interpretation/interpretation.service';
import {PaymentsService} from '../src/payments/payments.service';
import {AdminService} from '../src/admin/admin.service';
import {RateLimitService} from '../src/common/rate-limit.service';
process.loadEnvFile('.env');
const baseUrl=process.env.DATABASE_URL!;
const db='transligual_codex_test_'+randomBytes(6).toString('hex');
const adminDb=new PrismaClient({datasources:{db:{url:baseUrl}}});
let p:PrismaClient|undefined;
let created=false;
const realFetch=global.fetch;
async function run(){
 await adminDb.$executeRawUnsafe('CREATE DATABASE "'+db+'"');created=true;
 const testUrl=new URL(baseUrl);testUrl.pathname='/'+db;
 const env={...process.env,DATABASE_URL:testUrl.toString(),DIRECT_DATABASE_URL:testUrl.toString()};
 const migration=spawnSync(process.execPath,['node_modules/prisma/build/index.js','migrate','deploy'],{env,encoding:'utf8'});
 if(migration.status!==0)throw new Error('Migration failed: '+migration.stderr);
 p=new PrismaClient({datasources:{db:{url:testUrl.toString()}}});
 const prisma=p as any;
 const courseService=new CoursesService(prisma);
 const certificateService=new CertificatesService(prisma);
 const assessmentService=new AssessmentsService(prisma,certificateService);
 const learn=new LearningService(prisma,certificateService);
 const enroll=new EnrollmentsService(prisma);
 const interpret=new InterpretationService(prisma);
 const staff=new AdminService(prisma,courseService);
 const users=await Promise.all(['student','tutor','admin','worker','outsider'].map(name=>p!.user.create({data:{email:name+'@example.test',status:'ACTIVE',emailVerifiedAt:new Date(),roles:name==='admin'?['ADMIN']:name==='tutor'?['STUDENT','TUTOR']:['STUDENT'],profile:{create:{firstName:name,lastName:'Test'}}}})));
 const [student,tutor,admin,worker,outsider]=users;
 const tutorProfile=await p.tutorProfile.create({data:{userId:tutor.id,languages:['French']}});
 const category=await p.category.create({data:{name:'French',slug:'french'}});
 const input={title:'French test course',shortDescription:'A test course description',description:'A longer French course description for integration testing.',categoryId:category.id,level:'BEGINNER' as const,priceMinor:'0',currency:'NGN',certificateEnabled:true};
 await assert.rejects(()=>courseService.create(input,tutor.id,['TUTOR']));
 await staff.decideTutor(tutorProfile.id,true,admin.id);
 const course=await courseService.create(input,tutor.id,['TUTOR']);
 const section=await courseService.createModule(course.id,tutor.id,['TUTOR'],{title:'Foundations'});
 const lesson=await courseService.createLesson(section.id,tutor.id,['TUTOR'],{title:'Quiz',lessonType:'QUIZ'});
 await assert.rejects(()=>courseService.createModule(course.id,outsider.id,['TUTOR'],{title:'Intrusion'}));
 const q={text:'Bonjour means?',options:['Hello','Goodbye'],correct:[0],points:1};
 const assessment=await assessmentService.author(course.id,tutor.id,['TUTOR'],{title:'Greetings quiz',lessonId:lesson.id,passPercentage:70,maxAttempts:3,isPublished:true,questions:[q]});
 const exam=await assessmentService.author(course.id,tutor.id,['TUTOR'],{title:'Final exam',passPercentage:70,maxAttempts:2,durationMinutes:10,isPublished:true,questions:[q]});
 await courseService.submitForReview(course.id,tutor.id,['TUTOR']);await courseService.publish(course.id,admin.id);
 await assert.rejects(()=>learn.getCourse(student.id,course.id));
 await enroll.enrollFreeCourse(student.id,course.id);
 await assert.rejects(()=>learn.updateProgress(student.id,lesson.id,{progressPercentage:100,lastPositionSeconds:0}));
 const attempt=await assessmentService.start(assessment.id,student.id);
 assert.equal((await assessmentService.submit(attempt.id,student.id,{answers:[{question:0,selected:[1]}]})).passed,false);
 const retry=await assessmentService.start(assessment.id,student.id);
 assert.equal((await assessmentService.submit(retry.id,student.id,{answers:[{question:0,selected:[0]}]})).passed,true);
 await learn.updateProgress(student.id,lesson.id,{progressPercentage:100,lastPositionSeconds:0});
 assert.equal(await p.certificate.count(),0);
 const final=await assessmentService.start(exam.id,student.id);
 await assessmentService.submit(final.id,student.id,{answers:[{question:0,selected:[0]}]});
 const certificate=await p.certificate.findFirstOrThrow();assert.equal((await certificateService.verify(certificate.verificationCode)).valid,true);
 await Promise.all([certificateService.issueIfEligible(student.id,course.id),certificateService.issueIfEligible(student.id,course.id)]);
 assert.equal(await p.certificate.count(),1);
 console.log('PASS tutor approval, ownership, publish, enrollment, quiz gating, exam grading and unique certificate');
 const limits=new RateLimitService(prisma);await limits.consume('test',1,60000);await assert.rejects(()=>limits.consume('test',1,60000));
 console.log('PASS shared rate limit');
 await interpret.approveInterpreter({email:worker.email,languagePairs:'French-English',qualifications:'Test qualification'},admin.id);
 const service=await p.interpretationService.create({data:{name:'Online session',durationUnit:'hour'}});
 const booking=await interpret.createBooking(student.id,{serviceId:service.id,sourceLanguage:'fr',targetLanguage:'en',scheduledStartAt:new Date(Date.now()+86400000).toISOString(),scheduledEndAt:new Date(Date.now()+90000000).toISOString(),locationType:'ONLINE'});
 await interpret.manage(booking.id,admin.id,['ADMIN'],{action:'quote',amountMinor:'10000',currency:'NGN'});
 await assert.rejects(()=>interpret.manage(booking.id,admin.id,['ADMIN'],{action:'assign',interpreterId:worker.id}));
 let reference='';global.fetch=(async (url:any,init:any)=>{if(String(url).endsWith('/initialize')){reference=JSON.parse(init.body).reference;return {ok:true,json:async()=>({status:true,data:{reference,authorization_url:'https://checkout.paystack.com/test'}})};}
 return {ok:true,json:async()=>({status:true,data:{reference,status:'success',amount:10000,currency:'NGN'}})};}) as typeof fetch;
 const pay=new PaymentsService(prisma,{get:(key:string)=>key==='PAYSTACK_SECRET_KEY'?'sk_test_fake':undefined} as any);
 const checkout=await pay.initializeInterpretationCheckout(student.id,booking.id);
 await pay.verifyCoursePayment(student.id,checkout.reference);
 assert.equal((await p.interpretationBooking.findUniqueOrThrow({where:{id:booking.id}})).status,'CONFIRMED');
 await interpret.manage(booking.id,admin.id,['ADMIN'],{action:'assign',interpreterId:worker.id,meetingUrl:'https://example.test/session'});
 await interpret.manage(booking.id,worker.id,['INTERPRETER'],{action:'start'});
 await interpret.manage(booking.id,worker.id,['INTERPRETER'],{action:'deliver',notes:'Session completed'});
 await interpret.manage(booking.id,student.id,['STUDENT'],{action:'revise',notes:'Please clarify the final point'});
 await interpret.manage(booking.id,worker.id,['INTERPRETER'],{action:'start'});
 await interpret.manage(booking.id,worker.id,['INTERPRETER'],{action:'deliver',notes:'Clarification delivered'});
 await interpret.manage(booking.id,student.id,['STUDENT'],{action:'complete'});
 await pay.verifyCoursePayment(student.id,checkout.reference);
 assert.equal((await p.interpretationBooking.findUniqueOrThrow({where:{id:booking.id}})).status,'COMPLETED');
 console.log('PASS interpretation quote, mocked payment, assignment, delivery, revision, acceptance and replay');
}
run().catch(e=>{console.error(String(e.message).replaceAll(baseUrl,'[database]'));process.exitCode=1;}).finally(async()=>{global.fetch=realFetch;await p?.$disconnect();if(created&&/^transligual_codex_test_[a-f0-9]{12}$/.test(db))await adminDb.$executeRawUnsafe('DROP DATABASE "'+db+'" WITH (FORCE)');await adminDb.$disconnect();});

